
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 6;
  public static final int DIVIDEBY = 7;
  public static final int SIN = 12;
  public static final int PLUS = 3;
  public static final int RPAREN = 9;
  public static final int COS = 13;
  public static final int SEMI = 2;
  public static final int INT_NUMBER = 15;
  public static final int LPAREN = 8;
  public static final int LOG = 11;
  public static final int EXP = 10;
  public static final int DEC_NUMBER = 16;
  public static final int MEM = 17;
  public static final int EOF = 0;
  public static final int MINUS = 4;
  public static final int error = 1;
  public static final int EQ = 14;
  public static final int UMINUS = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "UMINUS",
  "TIMES",
  "DIVIDEBY",
  "LPAREN",
  "RPAREN",
  "EXP",
  "LOG",
  "SIN",
  "COS",
  "EQ",
  "INT_NUMBER",
  "DEC_NUMBER",
  "MEM"
  };
}

